name: main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Vet checks
        run: go vet -v ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v .

  conventional-commits:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.1.2

    - name: conventional commits
      uses: webiny/action-conventional-commits@v1.3.0
